# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
x.shape, x

(torch.Size([7, 7]),
 tensor([[0.3077, 0.4850, 0.4290, 0.2858, 0.1169, 0.2088, 0.7932],
         [0.2745, 0.9137, 0.4046, 0.1614, 0.8367, 0.3639, 0.4017],
         [0.5130, 0.7274, 0.4326, 0.6740, 0.3171, 0.7087, 0.6982],
         [0.7759, 0.1874, 0.7677, 0.0333, 0.0111, 0.3840, 0.7377],
         [0.7357, 0.6600, 0.1861, 0.3156, 0.7735, 0.0309, 0.8720],
         [0.7402, 0.6139, 0.7467, 0.5670, 0.9399, 0.7320, 0.9726],
         [0.2917, 0.9799, 0.2816, 0.1450, 0.7343, 0.7288, 0.2763]]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
y = torch.rand(1, 7)
y.shape , y
# Perform matrix multiplication
z = torch.matmul(x, y.T)
z

tensor([[1.1811],
        [2.0038],
        [1.8681],
        [1.1528],
        [2.1480],
        [2.6829],
        [2.0170]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
rand_tensor_a = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
rand_tensor_b = torch.rand(1, 7)

# Matrix multiply tensors
tensor_c = torch.matmul(rand_tensor_a, rand_tensor_b.T)
tensor_c, tensor_c.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
RANDOM_SEED = 1234
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_a = torch.rand(2, 3).to('cuda')

torch.manual_seed(RANDOM_SEED)
tensor_b = torch.rand(2, 3).to('cuda')

print(tensor_a == tensor_b)

tensor([[True, True, True],
        [True, True, True]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
tensor_c = torch.matmul(tensor_a, tensor_b.T)
tensor_c, tensor_c.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
max = torch.max(tensor_c)
print(f"Max: {max}")
min = torch.min(tensor_c)
print(f"Min: {min}")

# Find min


Max: 0.628727912902832
Min: 0.21611443161964417


### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
print(torch.argmax(tensor_c))

# Find arg min
print(torch.argmin(tensor_c))

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(1,1,1,10)
print(tensor_d, tensor_d.shape)

# Remove single dimensions
tensor_e = tensor_d.squeeze()
print(tensor_e, tensor_e.shape)
# Print out tensors and their shapes
print(f" \n \n Original tensor before squeeze: {tensor_d}")
print(f"Original tensor shape: {tensor_d.shape}")
print(f"\n \n Squeezed tensor: {tensor_e}")
print(f"Squeezed tensor shape: {tensor_e.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
 
 
 Original tensor before squeeze: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original tensor shape: torch.Size([1, 1, 1, 10])

 
 Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed tensor shape: torch.Size([10])
